# -*- coding: utf-8 -*-
"""Copy of Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r7mYG9EYjAUywIZ5Sm84yKc9vdrGsXAH
"""

# Python program to find current
# weather details of any city
# using openweathermap api

# import required modules
import requests, json
from datetime import datetime  

# Enter your API key here
api_key = 'c887420990404578bd1d8a5f1404cf97'

# Give city name
city_name = input("Enter city name : ")

# complete url address
complete_url = "http://api.openweathermap.org/data/2.5/weather?q=" +city_name +"&appid=" +api_key

# get method of requests module
# return response object
response = requests.get(complete_url)

# json method of response object
# convert json format data into
# python format data
x = response.json()

# Now x contains list of nested dictionaries
# Check the value of "cod" key is equal to
# "404", means city is found otherwise,
# city is not found
if x["cod"] != "404":
 
    # store the value of "main"
    # key in variable y
    y = x['main']
    # store the value corresponding
    # to the "temp" key of y
    current_temperature = y["temp"]
    current_temperature2 = y["temp"]-273.15
 
    # store the value corresponding
    # to the "pressure" key of y
    current_pressure = y["pressure"]
 
    # store the value corresponding
    # to the "humidity" key of y
    current_humidity = y["humidity"]
 
    # store the value of "weather"
    # key in variable z
    z = x["weather"]
 
    # store the value corresponding
    # to the "description" key at
    # the 0th index of z
    weather_description = z[0]["description"]
 
    # print following values
    print(" Temperature (in kelvin unit) = " +
                    str(current_temperature) +
          "\n Temperature (in Celcius unit) = " +
                    str(current_temperature2) +
          "\n atmospheric pressure (in hPa unit) = " +
                    str(current_pressure) +
          "\n humidity (in percentage) = " +
                    str(current_humidity) +
          "\n description = " +
                    str(weather_description))
 
else:
    print(" City Not Found ")